version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  s3:
    image: minio/minio
    restart: always
    volumes:
      - s3data:/data
    env_file:
      - s3.env
    command: --compat server /data

  app:
    build: ./nextcloud/16.0/fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - REDIS_HOST=redis
      - S3_HOST=s3
    env_file:
      - db.env
      - s3.env
    depends_on:
      - db
      - redis
      - s3

  web:
    build: ./web
    restart: always
    ports:
      - 80:80
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app

  cron:
    build: ./nextcloud/16.0/fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
      - s3


volumes:
  db:
  nextcloud:
  s3data:
